# append to automations.yaml

- alias: Sync Slider to Yamaha
  id: yamaha_vol_sync_to_unit
  trigger:
    platform: state
    entity_id: input_number.yamaha_volume_slider
  action:
  - service: rest_command.yamaha_main_set_volume
    data:
      volume: '{{ (states(''input_number.yamaha_volume_slider'') | float * 10) | int
        }}'
- id: yamaha_vol_sync_from_unit
  alias: Sync Yamaha to Slider
  triggers:
  - entity_id: sensor.yamaha_main_volume_raw
    trigger: state
  conditions:
  - condition: state
    entity_id: input_boolean.yamaha_volume_lock
    state:
    - 'off'
  actions:
  - target:
      entity_id: input_number.yamaha_volume_slider
    data:
      value: '{{ states(''sensor.yamaha_main_volume_raw'') | float / 10 }}'
    action: input_number.set_value
- id: yamaha_volume_lock_manager
  alias: Yamaha Volume Lock Manager
  description: Locks out reverse synchronization during rapid volume changes
  triggers:
  - entity_id: input_number.yamaha_volume_slider
    trigger: state
  conditions: []
  actions:
  - target:
      entity_id: input_boolean.yamaha_volume_lock
    action: input_boolean.turn_on
  - delay: '0:00:01.500'
  - target:
      entity_id: input_boolean.yamaha_volume_lock
    action: input_boolean.turn_off
  mode: restart
